### ISSUE TITLE
About topological_numbers

### ISSUE THREAD

**Issue by phcerdan** [ntustison/Utilities#1]
Hi @ntustison, I forked this Utilities looking for segmentation stuff, and I realized your code here in [topological_numbers](https://github.com/ntustison/Utilities/blob/master/src/topological_numbers.h). I am contributing some work to [DGtal](https://github.com/DGtal-team/DGtal/pull/1147) implementing work of G.Bertrand, and M.Couprie for skeletonization using ishtmuses.  I also contributed to LUT tables there for simplicity and isthmus, that greatly improves speed (there is a comment about this in your code).

Have you tried to contribute this branch of topology work into ITK? I chose DGtal because they had already implemented a lot of the needed framework for this, but always keen to contribute stuff to ITK.

Just curious!
Cheers

**Comment by ntustison** [comment]
Hi @phcerdan .  I'm pretty sure I got that code from [Segonne](http://florent.segonne.free.fr) but I don't have a link.  I used it when I was putting this [paper](https://www.ncbi.nlm.nih.gov/pubmed/21118779) together and needed to do a comparative evaluation.  I think I just put it in this repo in case I ever needed to reference it again.  We don't have much digital topology in ITK although I did put the well-composedness [stuff](http://www.insight-journal.org/browse/publication/121) in ITK's Insight Journal.  I also added the front propagation [aspect](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/FastMarching/include/itkFastMarchingImageFilterBase.hxx#L361-L1084) in ITK proper in the fast marching class.  

Hope that helps,
Nick

**Comment by phcerdan** [comment]
It does, thanks!
